file-watch: src/main.c src/impls/watched_folders.c src/impls/event_handler.c
	gcc -Isrc/includes -Wall -pedantic -Wextra src/main.c src/impls/watched_folders.c src/impls/event_handler.c -o build/file-watch
